// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HDV.Nhom2.Domain
{
    /// <summary>
    /// Thông tin dự án
    /// </summary>
    public partial class Project
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid CompanyId { get; set; }
        public string Description { get; set; }
    }
}